/* tools/import-census.js
 * Imports U.S. Census ACS state-level context into assets/data/census-data.js.
 *
 * SOURCE: U.S. Census Bureau, American Community Survey (ACS) 5-year estimates,
 *   via the public Census Data API — https://api.census.gov/data.html
 *   Variables:
 *     B19013_001E  Median household income (USD)
 *     B25064_001E  Median gross rent (USD/month)
 *     B25077_001E  Median value (owner-occupied units, USD)
 *     B01003_001E  Total population
 *
 * USAGE:
 *   # Live fetch (needs internet; CENSUS_API_KEY optional but recommended):
 *   CENSUS_YEAR=2023 CENSUS_API_KEY=xxxx node tools/import-census.js
 *
 *   # Offline / no network: the script keeps any existing census-data.js and
 *   exits cleanly, so the build never breaks.
 *
 * No network in this environment? Then median household income on the site stays
 * an illustrative placeholder (clearly labeled) until you run this with internet.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const https = require("https");
const N = require("./normalize-data");

const ROOT = path.resolve(__dirname, "..");
const DEST = path.join(ROOT, "assets/data/census-data.js");
const YEAR = process.env.CENSUS_YEAR || "2023";
const KEY = process.env.CENSUS_API_KEY || "";
const VARS = ["B19013_001E", "B25064_001E", "B25077_001E", "B01003_001E"];

function apiUrl() {
  const base = "https://api.census.gov/data/" + YEAR + "/acs/acs5";
  const get = "NAME," + VARS.join(",");
  let u = base + "?get=" + get + "&for=state:*";
  if (KEY) u += "&key=" + KEY;
  return u;
}

function fetchJson(url, depth) {
  depth = depth || 0;
  return new Promise((resolve, reject) => {
    if (depth > 5) { reject(new Error("too many redirects")); return; }
    const req = https.get(url, { timeout: 15000 }, (res) => {
      if ([301, 302, 303, 307, 308].includes(res.statusCode) && res.headers.location) {
        res.resume();
        resolve(fetchJson(res.headers.location, depth + 1));
        return;
      }
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => {
        if (/invalid_key/i.test(url) || /Invalid Key/i.test(data)) {
          reject(new Error("Census rejected the API key as invalid. New keys must be " +
            "ACTIVATED via the link in the signup email before they work — check that email, " +
            "then retry. Also confirm there are no stray spaces in CENSUS_API_KEY."));
          return;
        }
        if (/^\s*</.test(data)) { // some other HTML error page (e.g. "Missing Key")
          reject(new Error(KEY ? "non-JSON response from Census API" : "Census API requires a free API key (set CENSUS_API_KEY)"));
          return;
        }
        try { resolve(JSON.parse(data)); } catch (e) { reject(e); }
      });
    });
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(new Error("timeout")); });
  });
}

function write(records, vintage) {
  const banner = "/* census-data.js — AUTO-GENERATED by tools/import-census.js. Do not edit by hand.\n" +
    "   U.S. Census Bureau, American Community Survey (ACS) 5-year estimates.\n" +
    "   Source: https://www.census.gov/programs-surveys/acs/  API: https://api.census.gov/\n" +
    "   ACS year: " + vintage + ". Re-run the importer to refresh. */\n";
  fs.writeFileSync(DEST,
    banner + "window.HAM_CENSUS = " + JSON.stringify({
      vintage: "ACS 5-year " + vintage,
      source: "U.S. Census Bureau, American Community Survey",
      sourceUrl: "https://www.census.gov/programs-surveys/acs/",
      regions: records
    }) + ";\n");
}

// ---- Place + county import (for city/county pages) ---------------------- */
const DEST_PLACES = path.join(ROOT, "assets/data/census-places.js");

function buildUrl(forClause, inClause) {
  const base = "https://api.census.gov/data/" + YEAR + "/acs/acs5";
  let u = base + "?get=NAME," + VARS.join(",") + "&for=" + forClause;
  if (inClause) u += "&in=" + inClause;
  if (KEY) u += "&key=" + KEY;
  return u;
}

// Normalize a Census place NAME ("Baltimore city, Maryland") to a comparable
// "city|ST" key.
function placeKey(name) {
  const comma = name.lastIndexOf(",");
  let city = comma > -1 ? name.slice(0, comma) : name;
  const stName = comma > -1 ? name.slice(comma + 1).trim() : "";
  const m = N.stateMeta(stName);
  city = city.replace(/\s+(city|town|village|borough|municipality|CDP|\(balance\)|metro government \(balance\)|metropolitan government \(balance\)|urban county)$/i, "").trim();
  return m ? (city + "|" + m.abbr).toLowerCase() : null;
}

async function runPlaces() {
  // Load registry to know which cities (by name+state) and counties (by GEOID).
  global.window = {};
  eval(fs.readFileSync(path.join(ROOT, "assets/data/places-sample.js"), "utf8"));
  const REG = global.window.HAM_PLACES;
  const cities = REG.filter((p) => p.type === "city");
  const wantCity = {}; cities.forEach((p) => (wantCity[(p.zillow + "|" + p.stateAbbr).toLowerCase()] = p.slug));
  const stateFips = Array.from(new Set(cities.map((p) => {
    for (const k in N.STATE_INDEX) if (N.STATE_INDEX[k].abbr === p.stateAbbr) return N.STATE_INDEX[k].fips;
    return null;
  }).filter(Boolean)));

  const placeRecords = [];
  for (const sf of stateFips) {
    try {
      const rows = await fetchJson(buildUrl("place:*", "state:" + sf));
      const head = rows[0]; const idx = (k) => head.indexOf(k);
      for (let i = 1; i < rows.length; i++) {
        const r = rows[i];
        const key = placeKey(r[idx("NAME")]);
        const slug = key && wantCity[key];
        if (!slug) continue;
        const v = (k) => N.num(r[idx(k)]);
        placeRecords.push({
          slug: slug, name: r[idx("NAME")], type: "place",
          geoid: (r[idx("state")] || "") + (r[idx("place")] || ""),
          medianHouseholdIncome: v("B19013_001E"),
          medianGrossRent: v("B25064_001E"),
          population: v("B01003_001E")
        });
      }
    } catch (e) { console.warn("[import-census] place fetch failed for state " + sf + ": " + e.message); }
  }

  // Counties: one call for all counties, match registry county GEOIDs.
  const wantCounty = {}; REG.forEach((p) => { wantCounty[p.fips] = p.slug; });
  const countyRecords = [];
  try {
    const rows = await fetchJson(buildUrl("county:*", "state:*"));
    const head = rows[0]; const idx = (k) => head.indexOf(k);
    for (let i = 1; i < rows.length; i++) {
      const r = rows[i];
      const geoid = (r[idx("state")] || "") + (r[idx("county")] || "");
      if (!wantCounty[geoid]) continue;
      const v = (k) => N.num(r[idx(k)]);
      countyRecords.push({
        slug: wantCounty[geoid], name: r[idx("NAME")], type: "county", geoid: geoid,
        medianHouseholdIncome: v("B19013_001E"),
        medianGrossRent: v("B25064_001E"),
        medianOwnerValue: v("B25077_001E"),
        population: v("B01003_001E")
      });
    }
  } catch (e) { console.warn("[import-census] county fetch failed: " + e.message); }

  const banner = "/* census-places.js — AUTO-GENERATED by tools/import-census.js. Do not edit by hand.\n" +
    "   U.S. Census ACS 5-year (" + YEAR + ") place & county estimates. */\n";
  fs.writeFileSync(DEST_PLACES, banner + "window.HAM_CENSUS_PLACES = " + JSON.stringify({
    vintage: "ACS 5-year " + YEAR, source: "U.S. Census Bureau, American Community Survey",
    sourceUrl: "https://www.census.gov/programs-surveys/acs/",
    places: placeRecords, counties: countyRecords
  }) + ";\n");
  console.log("[import-census] wrote " + DEST_PLACES + " — " + placeRecords.length +
    " places, " + countyRecords.length + " counties (ACS " + YEAR + ").");
}

async function run() {
  try {
    const rows = await fetchJson(apiUrl());
    const head = rows[0];
    const idx = (k) => head.indexOf(k);
    const records = [];
    for (let i = 1; i < rows.length; i++) {
      const r = rows[i];
      const meta = N.stateMeta(r[idx("NAME")]);
      if (!meta) continue;
      const v = (k) => N.num(r[idx(k)]);
      records.push({
        abbr: meta.abbr, fips: meta.fips, name: r[idx("NAME")],
        medianHouseholdIncome: v("B19013_001E"),
        medianGrossRent: v("B25064_001E"),
        medianOwnerValue: v("B25077_001E"),
        population: v("B01003_001E")
      });
    }
    write(records, YEAR);
    console.log("[import-census] wrote " + DEST + " — " + records.length + " states (ACS " + YEAR + ").");
    await runPlaces();
  } catch (e) {
    console.warn("[import-census] live fetch failed (" + e.message + ").");
    if (fs.existsSync(DEST)) {
      console.warn("  Keeping existing census-data.js. Run with internet + CENSUS_API_KEY to refresh.");
    } else {
      console.warn("  No census-data.js yet — median income stays an illustrative placeholder.\n" +
        "  When online: CENSUS_YEAR=2023 CENSUS_API_KEY=xxxx node tools/import-census.js");
    }
  }
}

run();
